- name: Plugin Machine WordPress Plugin Builder
  # You may pin to the exact commit or the version.
  # uses: imaginarymachines/builder-action@7fdf020e97b55512bd6081723b3bc3996dfc7a33
  uses: imaginarymachines/builder-action@1.0.0
  with:
    # Plugin Machine Token
    PLUGIN_MACHINE_TOKEN: 
    # GitHub token
    GITHUB_TOKEN: 
    # Directory with plugin
    PLUGIN_DIR: # optional
    # If a link to ZIP should be added to PR
    COMMENT_PR: # optional
